version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    ports:
      - "3000:3000"
    environment:
      - PG_DB=carddb
      - PG_USER=cardadmin
      - PG_PASSWORD=cardadmin123
      - PG_HOST=node_db
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - node_db
  
  node_db:
    container_name: node_db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=carddb
      - POSTGRES_USER=cardadmin
      - POSTGRES_PASSWORD=cardadmin123
    volumes:
      - node_db_data:/var/lib/postgresql/data
volumes:
  node_db_data: {}



